[build-system]
build-backend = "poetry_dynamic_versioning.backend"
requires = [ "poetry-core>=1", "poetry-dynamic-versioning>=1,<2" ]

[project]
name = "cambium"
description = "A light touch markdown static site generator"
readme = "README.md"
license = "MIT"
license-files = [ "LICEN[CS]E*" ]
authors = [
  { name = "Sidrat Research", email = "info@sidratresearch.com" },
  { name = "Mubdi Rahman", email = "mubdi@sidratresearch.com" },
  { name = "Tai Withers", email = "tai@sidratresearch.com" },
  { name = "Hansen Jiang", email = "hansen@sidratresearch.com" },
  { name = "Jennifer Scora", email = "jscora@sidratresearch.com" },
]
requires-python = ">=3.11,<4.0"
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Content Management System",
  "Topic :: Internet :: WWW/HTTP :: Site Management",
  "Topic :: Text Processing :: Markup :: HTML",
  "Topic :: Text Processing :: Markup :: Markdown",
]
dynamic = [ "version" ]
dependencies = [
  "jinja2>=3.1.6,<4",
  "marko>=2.2.2,<3",
  "pagefind[extended]>=1.5.2",
  "pydantic>=2.13.4,<3",
  "python-slugify>=8.0.4,<9",
  "pyyaml>=6.0.3,<7",
  "typer>=0.25.1,<0.26",
]
urls.Homepage = "https://github.com/sidratresearch/cambium"
urls.Issues = "https://github.com/sidratresearch/cambium/issues"
scripts.cambium = "cambium.cli.cli:app"

[dependency-groups]
dev = [
  "black>=26.3.1,<27",
  "ipykernel>=7.2,<8",
  "isort>=8.0.1,<9",
  "pre-commit>=4.6,<5",
  "pytest>=9.0.3,<10",
  "tox>=4.53.1,<5",
]

[tool.poetry]
requires-plugins.poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = [
  "plugin",
] }
version = "0.0.0"

[tool.poetry-dynamic-versioning]
enable = true

[tool.pytest]
strict_xfail = true

[tool.tox]
env_list = [ { prefix = "3.", start = 11, stop = 14 } ]
requires = [ "tox>=4.53" ]
# env_run_base: defaults for *all* environments
env_run_base.package = "wheel"  # build a wheel and use it for all envs
env_run_base.wheel_build_env = ".pkg"  # re-use the wheel, built in an env called ".pkg"
env_run_base.description = "Run tests with pytest"
env_run_base.deps = [ "pytest>=9.0.3,<10" ]
env_run_base.commands = [
  [
    "pytest",
    { replace = "posargs", default = [
      "tests",
    ], extend = true },
  ],
]
