# Cambium 0.6.0.post211.dev0+d84ae0f default configuration
# Created with `cambium --dump-default-config`

domain_name: https://www.buildwithcambium.org
site_name: "Cambium: Static Site Generator"
subpath: "" # verify the absolute links in menu.md

theme: maple
theme_config:
  default_colour_mode: dark

stages:
  - PreviewCSV
  - IdentifyMetadata
  - WriteReports
  - TransformMarkdown
  - TemplateMarkdown
  - EnsureIndexPages
  - PagefindSearch
  - CheckLinks
